name: Deploy index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.125.6
    steps:
      - uses: actions/checkout@v4
      - name: Generate a list of plugins
        run: |
          mkdir -p site/data/v1 site/v1
          cat plugins/*.yaml > site/data/plugins.yaml
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb     
      - name: Install Dart Sass
        run: sudo snap install dart-sass          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            -s site \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
      - name: Store a yaml file for the plugin list
        run: |
          mkdir -p site/public/v1
          cp site/data/plugins.yaml site/public/v1
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/public
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
