name: Deploy index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p data/v1
          cat plugins/*.yaml > data/v1/index.yaml
      - uses: actions/upload-pages-artifact@v1
        with:
          path: data
          
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
